spring:
  application:
    name: UberProject-BookingService
  datasource:
    url: jdbc:mysql://localhost:3306/Uber_Db_Local
    username: root
    password: nonprod123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true

server:
  port: 8000

